name: standardize labels

on:
  push:
    branches:
      - master
    paths:
      - config/org-labels.json

jobs:
  standardize:
    name: standardize labels
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup gcloud for secret manager
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '276.0.0'
          service_account_key: ${{ secrets.GCP_SA_SECRETMANAGER_KEY_PROD }}
      
      - name: setup gcloud beta components
        run: gcloud components install beta
        shell: bash

      - name: export command to fetch github access token
        run: |
          echo "::set-env name=CMD_FETCH_GITHUB_PAT_CALLFORCEBOT::gcloud beta secrets versions access latest --secret=GITHUB_PAT_CALLFORCEBOT --quiet --project=callforce-prod"
        shell: bash

      - name: mask github access token
        run: echo "::add-mask::$(eval "$CMD_FETCH_GITHUB_PAT_CALLFORCEBOT")"
        shell: bash

      - name: export github access token
        run: echo "::set-env name=GITHUB_PAT_CALLFORCEBOT::$(eval "$CMD_FETCH_GITHUB_PAT_CALLFORCEBOT")"
        shell: bash

      - name: update organization labels
        uses: ./.github/actions/organization-labels-action
        id: org-labels
        with:
          org: callforce
          repo: .github
          token: ${{ env.GITHUB_PAT_CALLFORCEBOT }} 
          labelsPath: config/org-labels.json