name: test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - '.github/actions/**'

jobs:
  actions:
    name: actions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        action:
          - organization-labels-action
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-   

      - name: install dependencies
        run: npm install
        working-directory: .github/actions/${{ matrix.action }}

      - name: build action
        run: npm run build
        working-directory: .github/actions/${{ matrix.action }}

      - name: lint action
        run: npm run test
        working-directory: .github/actions/${{ matrix.action }}